### ISSUE TITLE
Can't create the role assignment

### ISSUE THREAD

**Issue by pmav99** [kaneuffe/azure-batch-workshop#1]
Hello Kai

I cannot run the first command from 01:
```
az role assignment create \
    --assignee MicrosoftAzureBatch \
    --role contributor
```
The error message is:

```
Cannot find user or service principal in graph database for 'MicrosoftAzureBatch'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id MicrosoftAzureBatch'.
```

My understanding is that this is not really needed, since I have already done this step from the web portal, nevertheless I was getting this error even before I created the role-assignment. Furthermore, the error is not related to an existing role assignment or something similar. 

After I comment out this line the scripts executes without problems.

```
$ az --version
azure-cli                         2.33.0

core                              2.33.0
telemetry                          1.0.6

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location '/opt/azure-cli/bin/python'
Extensions directory '/home/panos/.azure/cliextensions'

Python (Linux) 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

**Comment by kaneuffe** [comment]
Hi Panos,

You can ignore that one. In you case having the "Microsoft Azure Batch" as contributor should be the same.

Best regards,

Kai

Dr. Kai Neuffer
(he/him/his)
Global Black Belt Sr. Specialist HPC - EMEA Apps & Infra - SPAIN
+34 699 104 185 | +34 (91) 3919551 | ***@***.******@***.***> | aka.ms/hpc


***@***.***
***@***.******@***.******@***.***

From: pmav99 ***@***.***>
Sent: viernes, 11 de febrero de 2022 10:44
To: kaneuffe/azure-batch-workshop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kaneuffe/azure-batch-workshop] Can't create the role assignment (Issue #1)


Hello Kai

I cannot run the first command from 01:

az role assignment create \

    --assignee MicrosoftAzureBatch \

    --role contributor

The error message is:

Cannot find user or service principal in graph database for 'MicrosoftAzureBatch'. If the assignee is an appId, make sure the corresponding service principal is created with 'az ad sp create --id MicrosoftAzureBatch'.

My understanding is that this is not really needed, since I have already done this step from the web portal, nevertheless I was getting this error even before I created the role-assignment. Furthermore, the error is not related to an existing role assignment or something similar.

After I comment out this line the scripts executes without problems.

az --version

azure-cli                         2.33.0



core                              2.33.0

telemetry                          1.0.6



Dependencies:

msal                              1.16.0

azure-mgmt-resource               20.0.0



Python location '/opt/azure-cli/bin/python'

Extensions directory '/home/panos/.azure/cliextensions'



Python (Linux) 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]



Legal docs and information: aka.ms/AzureCliLegal



Your CLI is up-to-date.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkaneuffe%2Fazure-batch-workshop%2Fissues%2F1&data=04%7C01%7CKai.Neuffer%40microsoft.com%7C8fc09861f5c94d5269d208d9ed43088a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801694467186899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Rf6nQQ8QQQdXE9xP5pzVeYEqQJbrNiPPJm%2BffQchg5g%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANUA77ABIGFN6AD3WUJ4DEDU2TK6BANCNFSM5ODWBHAA&data=04%7C01%7CKai.Neuffer%40microsoft.com%7C8fc09861f5c94d5269d208d9ed43088a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801694467236884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rMdkfhbm4jUYYlsP1RXI9U04WZj5U3xRbh81G7PoQRY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CKai.Neuffer%40microsoft.com%7C8fc09861f5c94d5269d208d9ed43088a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801694467236884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WlQqZThvRESDt31FrVSd7NhU1Q2I9KxuCc4eYwfC4Wc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CKai.Neuffer%40microsoft.com%7C8fc09861f5c94d5269d208d9ed43088a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637801694467236884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c9leoHgI8yKNnnV1L3azsYieWNyBXuIR%2BttaefsqRHM%3D&reserved=0>.

**Comment by kaneuffe** [comment]
I changed the account creation script and it should now work.
